package com.quotemaster.quotemasterapp.utils

enum class Author(val displayName: String) {
    SHAKESPEARE("William Shakespeare"),
    TWAIN("Mark Twain"),
    AUSTEN("Jane Austen"),
    DICKENS("Charles Dickens"),
    DOSTOEVSKY("Fyodor Dostoevsky"),
    TOLSTOY("Leo Tolstoy"),
    WOOLF("Virginia Woolf"),
    ORWELL("George Orwell"),
    HUXLEY("Aldous Huxley"),
    HEMINGWAY("Ernest Hemingway"),
    FITZGERALD("F. Scott Fitzgerald"),
    ROWLING("J.K. Rowling"),
    TOLKIEN("J.R.R. Tolkien"),
    MARTIN("George R.R. Martin"),
    MURAKAMI("Haruki Murakami"),
    KAFKA("Franz Kafka"),
    WILDE("Oscar Wilde"),
    DICKINSON("Emily Dickinson"),
    EMERSON("Ralph Waldo Emerson"),
    THOREAU("Henry David Thoreau"),
    GIBRAN("Kahlil Gibran"),
    LEWIS("C.S. Lewis"),
    KAZANTZAKIS("Nikos Kazantzakis"),
    RUMI("Rumi"),
    CONFUCIUS("Confucius"),
    LAO_TZU("Lao Tzu"),
    VOLTAIRE("Voltaire"),
    KIERKEGAARD("Søren Kierkegaard"),
    NIETZSCHE("Friedrich Nietzsche"),
    FREUD("Sigmund Freud"),
    JUNG("Carl Jung"),
    RUSSELL("Bertrand Russell"),
    SARTRE("Jean-Paul Sartre"),
    DE_BEAUVOIR("Simone de Beauvoir"),
    PLATO("Plato"),
    ARISTOTLE("Aristotle"),
    SOCRATES("Socrates"),
    BUDDHA("Buddha"),
    GANDHI("Mahatma Gandhi"),
    MANDELA("Nelson Mandela"),
    KING("Martin Luther King Jr."),
    MALCOLM_X("Malcolm X"),
    DU_BOIS("W.E.B. Du Bois"),
    BALDWIN("James Baldwin"),
    ANGELOU("Maya Angelou"),
    MORRISON("Toni Morrison"),
    HURSTON("Zora Neale Hurston"),
    HUGHES("Langston Hughes"),
    ROOSEVELT("Eleanor Roosevelt"),
    KELLER("Helen Keller"),
    CURIE("Marie Curie"),
    HAWKING("Stephen Hawking"),
    SAGAN("Carl Sagan"),
    NEWTON("Isaac Newton"),
    GALILEO("Galileo Galilei"),
    DA_VINCI("Leonardo da Vinci"),
    MICHELANGELO("Michelangelo"),
    VAN_GOGH("Vincent van Gogh"),
    PICASSO("Pablo Picasso"),
    DALI("Salvador Dali"),
    WARHOL("Andy Warhol"),
    DISNEY("Walt Disney"),
    JOBS("Steve Jobs"),
    MUSK("Elon Musk"),
    GATES("Bill Gates"),
    EINSTEIN("Albert Einstein"),
    TESLA("Nikola Tesla"),
    EDISON("Thomas Edison"),
    FEYNMAN("Richard Feynman"),
    MARCUS("Marcus Aurelius"),
    EPICTETUS("Epictetus"),
    SENECA("Seneca"),
    OBAMA("Barack Obama"),
    T_ROOSEVELT("Theodore Roosevelt"),
    LINCOLN("Abraham Lincoln"),
    CHURCHILL("Winston Churchill"),
    JFK("John F. Kennedy"),
    FRANKLIN_R("Franklin D. Roosevelt"),
    LENIN("Vladimir Lenin"),
    MARX("Karl Marx"),
    SMITH("Adam Smith"),
    LOCKE("John Locke"),
    JEFFERSON("Thomas Jefferson"),
    FRANKLIN("Benjamin Franklin"),
    MILTON("John Milton"),
    HOMER("Homer"),
    DANTE("Dante Alighieri"),
    VIRGIL("Virgil"),
    HORACE("Horace"),
    OVID("Ovid"),
    SOPHOCLES("Sophocles"),
    AESCHYLUS("Aeschylus"),
    EURIPIDES("Euripides"),
    CHAUCER("Geoffrey Chaucer"),
    BYRON("Lord Byron"),
    WORDSWORTH("William Wordsworth"),
    COLERIDGE("Samuel Taylor Coleridge"),
    SHELLEY("Percy Bysshe Shelley"),
    KEATS("John Keats"),
    ELIOT("T.S. Eliot"),
    FROST("Robert Frost"),
    POUND("Ezra Pound"),
    AUDEN("W.H. Auden"),
    PLATH("Sylvia Plath"),
    FRANK("Anne Frank"),
    HESSE("Hermann Hesse"),
    SAINT_EXUPERY("Antoine de Saint-Exupéry"),
    COELHO("Paulo Coelho"),
    TOLLE("Eckhart Tolle");

    companion object {
        fun existsWithDisplayName(name: String): Boolean {
            return entries.any { it.displayName.equals(name, ignoreCase = true) }
        }
    }
}
